
export const REQUIRED_RESIDENCE_YEARS = 5;
export const MAX_TOTAL_ABROAD_DAYS_COUNTED = 365;
export const MAX_ABROAD_DAYS_IN_FINAL_YEAR = 90;
export const CONTINUOUS_ABSENCE_YEARS_LIMIT = 5;
export const MS_IN_DAY = 1000 * 60 * 60 * 24;
export const REQUIRED_RESIDENCE_DAYS = REQUIRED_RESIDENCE_YEARS * 365.25;
